# Generated by Django 2.0.9 on 2018-10-02 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_managed404', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagenotfoundentry',
            name='redirect_to_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page'),
        ),
    ]
